[package]
name = "gilvave-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
keyring.workspace = true
time.workspace = true
web-sys.workspace = true
thiserror = "2.0.18"
uuid = { version = "1.23.1", features = ["v4", "v7", "serde", "js"] }
sysinfo = "0.39.6"
woothee = "0.13.0"
