[package]
name = "gilvave-http"
version.workspace = true
edition.workspace = true

[dependencies]
tauri.workspace = true
tauri-plugin-http.workspace = true
serde.workspace = true
serde_json.workspace = true
futures-util.workspace = true
tracing.workspace = true

gilvave-core = { path = "../core" }
gilvave-gateway = { path = "../gateway" }
gilvave-state = { path = "../state" }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
time.workspace = true
